# services:
#   # backend:
#   #   image: mailov-adventures-b:latest
#   #   container_name: mailov-adventures-b
#   #   build:
#   #     context: ./
#   #     dockerfile: Dockerfile
#   #   environment:
#   #     NODE_ENV: production
#   #     DB_HOST: db
#   #     DB_PORT: ${DB_PORT}
#   #     DB_USER: ${DB_USER}
#   #     DB_PASSWORD: ${DB_PASSWORD}
#   #     DB_NAME: ${DB_NAME}
#   #   env_file:
#   #     - .env
#   #   ports:
#   #     - "${PORT}:${PORT}"
#   #   depends_on:
#   #     db:
#   #       condition: service_healthy
#   #   networks:
#   #     - app-network

#   db:
#     image: postgres:14
#     container_name: postgres_db
#     env_file:
#       - .env
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}
#     ports:
#       - "${DB_PORT}:${DB_PORT}"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - app-network
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   postgres_data:
